config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :songs, only: %i[new create index]
  resources :artists
  resources :albums

  root 'artists#index'
end

app/models/album.rb
class Album < ApplicationRecord
    belongs_to :artist
    has_many :songs
    has_one_attached :image
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :songs
    has_many :albums
    belongs_to :user, optional: true
    has_one_attached :image
end

app/models/song.rb
class Song < ApplicationRecord
    include SongUploader[:track]

    validates :title, presence: true
    validates :artist, presence: true
    validates :track, presence: true

    acts_as_taggable # Alias for acts_as_taggable_on :tags
    acts_as_taggable_on :genre, :instruments, :mood

    belongs_to :artist
    belongs_to :album
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  acts_as_tagger
  has_one :artist
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def show
  end

  def new
    @album = Album.new
    @artist = Artist.find(params['artist'])
  end

  def create
    @album = Album.new album_params
    if @album.save
      redirect_to edit_artist_path(@album.artist)
    else
      render :new
    end
  end

  def edit
    @album = Album.find(params['id'])
    @artist = @album.artist
  end

  def update
    @album = Album.find(params['id'])
    if @album.update_attributes(album_params) && attach_image
      flash[:success] = "Album updated"
      redirect_to edit_artist_path(@album.artist)
    else
      render 'edit'
    end
  end

  def delete
  end
end

private

def attach_image
  @album.image.attach(album_params[:image]) if album_params[:image].present?
  true
end

def album_params
  params.require(:album).permit(:title, :artist_id, :image)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

    def index
        @artists = Artist.all
    end

    def show
        @artist = Artist.find(params['id'])
        @songs = Song.where(artist: @artist)
    end

    def new
        @artist = Artist.new
    end

    def create
        @artist = Artist.new song_params
        if @artist.save
          redirect_to artists_path
        else
          render :new
        end
    end

    def edit
        @artist = Artist.find(params['id'])
    end

    def update
        @artist = Artist.find(params['id'])
        if @artist.update_attributes(artist_params) && attach_image
          flash[:success] = "Artist updated"
          redirect_to @artist
        else
          render 'edit'
        end
      end

    private

    def attach_image
        @artist.image.purge
        @artist.image.attach(artist_params[:image]) if artist_params[:image].present?
        true
    end


    def artist_params
        params.require(:artist).permit(:name, :website, :bio, :location, :image)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
      @songs = Song.all
  end

  def new
      @song = Song.new
      @artist = Artist.find(params['artist'])
  end

  def create
      @song = Song.new song_params
      if @song.save
        redirect_to edit_artist_path(@song.artist)
      else
        render :new
      end
  end

  private

  def song_params
      params.require(:song).permit(:title, :artist_id, :track, :tag_list)
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/albums/_form.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-5 col-md-offset-3 border">
        <%= form_for(@album) do |f| %>
        <%= f.hidden_field :artist_id, :value => @artist.id %>

        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>

        <% if @album.image.attachment.present? %>
          <%= image_tag(@album.image, class: 'img-fluid') %><br>
        <% end %>
        <%= f.label :image %>
        <%= f.file_field :image, class: 'form-control' %>

        <%= f.submit "Save changes", class: "btn btn-primary" %>
        <% end %>
    </div>
  </div>
</div>

app/views/albums/edit.html.erb
<%= render 'form' %>

app/views/albums/new.html.erb
<h3>Add album for <%= @artist.name %></h3>
<%= render 'form' %>

app/views/albums/show.html.erb
<h1>Albums#show</h1>
<p>Find me in app/views/albums/show.html.erb</p>

app/views/artists/edit.html.erb
<h1>Update your artist profile</h1>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-5 col-md-offset-3 border">
        <%= form_for(@artist) do |f| %>

        <div class="form-group row">
          <%= f.label :name, class: 'col-3 col-form-label'%>
            <div class="col-9">
              <%= f.text_field :name, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group row">
          <%= f.label :location, class: 'col-3 col-form-label'%>
            <div class="col-9">
              <%= f.text_field :location, class: 'form-control' %>
            </div>
        </div>
        <div class="form-group row">
          <%= f.label :website, class: 'col-3 col-form-label'%>
            <div class="col-9">
              <%= f.text_field :website, class: 'form-control' %>
            </div>
        </div>

        <%= f.label :bio %>
        <%= f.text_area :bio, class: 'form-control' %>

        <% if @artist.image.attachment.present? %>
          <%= image_tag(@artist.image, class: 'img-fluid') %><br>
        <% end %>
        <%= f.label :image %>
        <%= f.file_field :image, class: 'form-control' %>

        <%= f.submit "Save changes", class: "btn btn-primary" %>
        <% end %>
    </div>
    <div class="col-7 border">
      <h4>Current Songs
        <span><%= link_to 'Add album',
                  new_album_path(artist: @artist),
                  class: 'btn btn-sm btn-primary' %></span>
        <span><%= link_to 'Add song',
                  new_song_path(artist: @artist),
                  class: 'btn btn-sm btn-primary' %></span>

      </h4>

        <div class="border rounded">
          <table>
            <% @artist.albums.each do |album| %>
                <h6>
                  <%= album.title %>
                  <span><%= link_to 'Edit', edit_album_path(album), class: 'btn btn-sm btn-primary' %></span>
                </h6>
                <hr>
                <% album.songs.each do |song| %>
                  <tr>
                    <td class="align-middle"><p><strong><%= song.title %></strong></p></td>
                    <td>
                      <audio controls>
                        <source src="<%= song.track.url %>" type="audio/mp3">
                      </audio>
                    </td>
                  </tr>
                <% end %>
            <% end %>
          </table>
        </div>
    </div>
  </div>
</div>

app/views/artists/index.html.erb
<div class="container">
  <div class="card-columns">
    <% @artists.each do |artist| %>
      <div class="card">
        <% if artist.image.attachment.present? %>
          <%= image_tag(artist.image, class: 'card-img-top', alt: 'Card image cap') %>
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= link_to(artist&.name, artist_path(artist)) %></h5>
          <small><i><p class="card-text"><%= artist&.location %></p></i></small>
          <small><p class="card-text"><%= artist&.bio %></p></small>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/artists/show.html.erb
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-5">
        <h1><%= @artist.name %></h1>
        <% if @artist.image.attachment.present? %>
          <%= image_tag(@artist.image, class: 'img-fluid') %>
        <% end %>
      </div>
      <div class="col-7">
        <table class="table table-hover table-sm table-responsive-sm">
          <tbody>
            <%= render @songs %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>CommonSound Admin</title>
  <%= csrf_meta_tags %>

  <%= javascript_include_tag 'admin', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Commonsound</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#"><%= link_to 'CommonSound', songs_path, :class => 'navbar-brand' %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="<%= artists_path %>">Artists</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= songs_path %>">Songs</a>
          </li>
          <%# <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li> %>
        </ul>
        <ul class="navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class="nav-item">
              <a class="nav-link" href="<%= edit_user_registration_path %>">My Account<span class="sr-only"></span></a>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "nav-link"%><span class="sr-only"></span>
            </li>
          <% else %>
            <li class="nav-item">
              <a class="nav-link" href="<%= new_user_session_path %>">Sign in<span class="sr-only"></span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= new_user_registration_path %>">Sign up<span class="sr-only"></span></a>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </head>

  <body style="background-color: #FCFEFF">
    <%= yield %>
  </body>
</html>

app/views/songs/_form.html.erb
<%= form_with model: song do |f| %>

  <%= f.hidden_field :artist_id, :value => @artist.id %>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :album %>
    <%= f.collection_select :album_id, @artist.albums, :id, :title %>
  </div>

  <div>
    <%= f.label :track %>
    <%= f.file_field :track %>
  </div>

  <%= f.submit %>
<% end %>

<%= link_to("Back", edit_artist_path(@artist)) %>

app/views/songs/_song.html.erb
<div>
  <tr>
    <td class="align-middle"><p><strong><%= song.title %></strong></p></td>
    <td class="align-middle">
      <p><strong>
        <% if song.artist.present? %>
          <%= link_to(song.artist&.name, artist_path(song.artist)) %>
        <% end %>
      </strong></p></td>
    <td>
      <audio controls>
        <source src="<%= song.track.url %>" type="audio/mp3">
      </audio>
    </td>
  </tr>
</div>

app/views/songs/index.html.erb
<div class="container-fluid">
  <h1>Songs</h1>
  <table class="table table-hover">
    <tbody>
      <%= render @songs %>
    </tbody>
  </table>
</div>

app/views/songs/new.html.erb
<h1>Add song for <%= @artist.name %></h1>
<%= render 'form', song: @song %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_user_session_path %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_user_registration_path %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_user_password_path %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>